### ISSUE TITLE
0.4-rc3.9 release

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4s#90]
- [x] update nd4j to 0.4-rc3.9
- [x] disable IComplexNDArray API since it's un-maintained atm
- [x] avoid using NDArray#setOrder API, which has a bug: https://github.com/deeplearning4j/nd4j/issues/982 
- [ ] fix NDArrayIndex bug: https://github.com/deeplearning4j/nd4j/issues/981
- [ ] follow Ops API change https://github.com/deeplearning4j/nd4s/issues/91

**Comment by agibsonccc** [comment]
Try again?

**Comment by saudet** [comment]
Superseded by #93
